### ISSUE TITLE
terminated by signal SIGILL

### ISSUE THREAD

**Issue by finestructure** [pointfreeco/swift-enum-properties#6] opened 2020-01-19 10:22 UTC
When running `generate-enum-properties` over a file with the ComposableArchitecture code from the SwiftUI series I got a crash:

```
 ~/D/p/PFPrime  ⎇ master ~  generate-enum-properties -n PFPrime/Misc/Arch.swift
Fatal error: Error raised at top level: SwiftSyntax.TokenKind.DecodeError.unknownTokenKind("ellipsis"): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.8.280/swift/stdlib/public/core/ErrorType.swift, line 200
fish: 'generate-enum-properties -n PFP…' terminated by signal SIGILL (Illegal instruction)
 !  ~/D/p/PFPrime  ⎇ master ~  swift --version
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.2.0
 ~/D/p/PFPrime  ⎇ master ~  generate-enum-properties --version
0.1.0
```

The file has the following content:

```
 ~/D/p/PFPrime  ⎇ master ~  cat PFPrime/Misc/Arch.swift
//
//  Arch.swift
//  PFPrime
//
//  Created by Sven A. Schmidt on 19/01/2020.
//  Copyright © 2020 finestructure. All rights reserved.
//

import Foundation


final class Store<Value, Action>: ObservableObject {
    @Published var value: Value
    let reducer: (inout Value, Action) -> Void

    init(initialValue: Value, reducer: @escaping (inout Value, Action) -> Void) {
        self.value = initialValue
        self.reducer = reducer
    }

    func send(_ action: Action) {
        reducer(&value, action)
    }
}


func combine<Value, Action>(
  _ reducers: (inout Value, Action) -> Void...
) -> (inout Value, Action) -> Void {

  return { value, action in
    for reducer in reducers {
      reducer(&value, action)
    }
  }
}


func pullback<LocalValue, GlobalValue, Action>(
    _ reducer: @escaping (inout LocalValue, Action) -> Void,
    get: @escaping (GlobalValue) -> LocalValue,
    set: @escaping (inout GlobalValue, LocalValue) -> Void
) -> (inout GlobalValue, Action) -> Void {

    return  { globalValue, action in
        var localValue = get(globalValue)
        reducer(&localValue, action)
        set(&globalValue, localValue)
    }
}

func pullback<LocalValue, GlobalValue, Action>(
    _ reducer: @escaping (inout LocalValue, Action) -> Void,
    value: WritableKeyPath<GlobalValue, LocalValue>
) -> (inout GlobalValue, Action) -> Void {
    return { globalValue, action in
        reducer(&globalValue[keyPath: value], action)
    }
}
```

It's obviously easy enough not to include that file so it's not a dealbreaker :)

I'll see if I can break this down further and find out what's tripping it up exactly.

**Comment by mbrandonw** [comment] 2020-01-20 14:03
Interesting!

We'll have to look into this more, but I can't help but notice that the error message mentions `SwiftSyntax.TokenKind.DecodeError.unknownTokenKind("ellipsis")` and there is an ellipsis used for the variadics in `combine` 🤔

**Comment by finestructure** [comment] 2020-01-20 14:08
Hah. I saw the error message but failed to spot the `...` in the `combine` method when I looked for variadics in the file. Retrying with it commented out avoids the crash - so that's it.

I tried with the method signature reformatted to avoid the line break, i.e. `Void...)` but that crashes as well.

**Comment by mbrandonw** [comment] 2020-01-20 14:14
Good to know! If it's a bug on our end we'll try to fix, and if it's a bug in SwiftSyntax maybe we can just update to a newer version.

Thanks for letting us know!

**Comment by stephencelis** [comment] 2021-08-16 18:26
This seems to be a duplicate of #5, so going to close in favor of that. Sorry for letting this one sit so long! We've had a lot of work to prioritize 😅

**Closed as completed by stephencelis** 2021-08-16 18:26 UTC
Labels: duplicate
